local GuiUtils = {
    AcrylicBlur  = require("@self/AcrylicBlur"),
    Colors       = require("@self/Colors"),
    Create       = require("@self/Create"),
    Event        = require("@self/Event"),
    Input        = require("@self/Input"),
    Interactions = require("@self/Interactions"),
    Lucide       = require("@self/Lucide"),
    MISC         = require("@self/MISC"),
    Monitoring   = require("@self/Monitoring"),
    Strings      = require("@self/Strings"),
    Unscaling    = require("@self/Unscaling")
}

return GuiUtils
